In [2]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
df=pd.read_csv('sms.csv',sep='\t',names=['Status','Message'])


In [4]:
df.head()


Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
len(df)


5572

In [6]:
len(df[df.Status=='spam'])


747

In [7]:
len(df[df.Status=='ham'])


4825

In [8]:
df.loc[df["Status"]=='ham',"Status",]=1


In [9]:
df.loc[df["Status"]=='spam',"Status",]=0


In [10]:
df.head()


Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [11]:
df_x=df["Message"]
df_y=df["Status"]

In [12]:
cv = TfidfVectorizer(min_df=1,stop_words='english')


In [15]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)


In [16]:
len(x_test)

1115

In [17]:
x_train.head()


1457    U sleeping now.. Or you going to take? Haha.. ...
472     How long has it been since you screamed, princ...
2481    Urgent! call 09066612661 from landline. Your c...
243     Okay. No no, just shining on. That was meant t...
1413    Wen ur lovable bcums angry wid u, dnt take it ...
Name: Message, dtype: object

In [ ]:
cv = TfidfVectorizer(min_df=1,stop_words='english')
x_traincv = cv.fit_transform(["Hi How are you How are you doing","Hi what's up","Wow that's awesome"])
feature_names = cv.get_feature_names()

# Print the feature names and the TF-IDF matrix
print(feature_names)
print(x_traincv.toarray())

['awesome', 'doing', 'hi', 'wow']
[[0.         0.79596054 0.60534851 0.        ]
 [0.         0.         1.         0.        ]
 [0.70710678 0.         0.         0.70710678]]


In [18]:
cv1 = TfidfVectorizer(min_df=1,stop_words='english')


In [19]:
x_traincv=cv1.fit_transform(x_train)
a=x_traincv.toarray()
a[0]


array([0., 0., 0., ..., 0., 0., 0.])

In [20]:
x_testcv=cv1.transform(x_test)
x_testcv.toarray()


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
 mnb = MultinomialNB()


In [22]:
y_train=y_train.astype('int')
y_train


1457    1
472     1
2481    0
243     1
1413    1
       ..
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4457, dtype: int64

In [23]:
mnb.fit(x_traincv,y_train)


MultinomialNB()

In [ ]:
#testmessage=x_test.iloc[0]
#testmessage

'somewhere out there beneath the pale moon light someone think in of u some where out there where dreams come true... goodnite &amp; sweet dreams'

In [24]:
predictions=mnb.predict(x_testcv)


In [25]:
predictions


array([1, 1, 1, ..., 1, 1, 0])

In [26]:
a=np.array(y_test)
a

array([1, 1, 1, ..., 1, 1, 0], dtype=object)

In [27]:
count=0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [28]:
count


1068

In [29]:
len(predictions)


1115

In [30]:
1068/1115.0


0.957847533632287